### PR TITLE
Upgrade linting

### LINKED ISSUE #14: Adopt Airbnb javascript guide (or some other more complete jslint ruleset)
https://github.com/airbnb/javascript

They include jslint rules. We need better jslint rules!

### PR DESCRIPTION
**Pull request by tschuy**
Fixes #14 

I grabbed a few of my favorite ones and stuck them in. Going to go through the project and fix thigns before we merge this.

### CODE REVIEW

**Comment by iankronquist** [comment]
Any particular reason for 100 character line lengths and not the more traditional 80? "I like it better" is good enough for me. Also, does `indent: 4` really enforce 2 space indentation? http://jshint.com/docs/options/#indent
Also, what do you think of that little warning in the docs?

**Comment by tschuy** [comment]
Oops. Copied that comment from the AirBnb guide and changed it to 4 without changing the comment.

I chose 100 because 100 can be limiting at times. I think we should still stick to 80, unless we have a good reason, but enforcing 80 leads to things where we line break in awkward places simply to avoid the linter blowing up in our faces.

Thoughts?

**Comment by tschuy** [comment]
One problem I have is that we already have lines of up to 95 characters. But that won't be too bad to fix.

**Comment by tschuy** [comment]
@iankronquist @LyonesGamer @ElijahCaine @Kennric We have to decide how long we want the line length to be. 80 is normal, but if we set it to 100, we can have files like ```src/checkins.js``` without unnecessary line breaks.

**Comment by tschuy** [comment]
I've set it back to 100. Files like ```src/checkins.js``` look multiple times better with 100 character line limits. I'm open to comments.

**Comment by tschuy** [comment]
I added jscs, the other big javascript tool. Lots of places use both, since jscs is for style and jshint is more for actual issues.

I used the Airbnb template included in the jscs repo, with some changes to reflect my thoughts on styling. Woo personal opinion!

**Comment by tschuy** [comment]
@iankronquist check out #19 to see what it'd look like to set the line limit to 80.

**Comment by ElijahCaine** [comment]
``npm test`` and ``npm run linter`` both pass. :+1: looks good to me.

**Comment by ElijahCaine** [comment]
Ran tests and the linter. Everything passes, looks good to me :+1:

**Pull request merged**
